### PR TITLE
v1.0.0 convert to app

### PR DESCRIPTION
**Pull request by sophie22**
make applet into an app by adding required fields, rename in dxapp.json to remove version
remove defaults for annotation tracks.

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_prep/2)

### CODE REVIEW

**Comment by sophie22** [comment]
example of running app in DNAnexus: https://platform.dnanexus.com/projects/G8x02384xVp3Qvj73P3ZxKjK/monitor/job/G8xXz3j4xVp2yG553J0096Zj

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_prep/2)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @jethror1 and @sophie22)

___
*[src/GATK_prep.sh, line 55 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_prep/2#-Mz_8Cyw-Xb_xqk4BjfF:-Mz_8Cyw-Xb_xqk4BjfG:budy51r) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_prep/blob/e0a0875d6661a93ddc03c64715ae9bb4bcf7b635/src/GATK_prep.sh#L55)):*
> ```Shell
>             sort -k1V -k2n segdup.bed > segmental_duplication.bed
>         else
>             echo "No segmental duplication track was provided, cannot annotate without it"
> ```

are you meant to exit here?

**Review by sophie22 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_prep/2)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[src/GATK_prep.sh, line 55 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_prep/2#-Mz_8Cyw-Xb_xqk4BjfF:-Mz_uDnz7u5BSZVnAMPd:b-45hqs1) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_prep/blob/e0a0875d6661a93ddc03c64715ae9bb4bcf7b635/src/GATK_prep.sh#L55)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

are you meant to exit here?
</blockquote></details>

maybe no, just notify the user that even though seg dup annotation was requested, if no file is provided the job will proceed without it

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_prep/2)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @jethror1 and @sophie22)

___
*[src/GATK_prep.sh, line 55 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_prep/2#-Mz_8Cyw-Xb_xqk4BjfF:-Mz_vXQeE6TsyGuz1oFO:b-oef1t1) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_prep/blob/e0a0875d6661a93ddc03c64715ae9bb4bcf7b635/src/GATK_prep.sh#L55)):*
<details><summary><i>Previously, sophie22 wrote…</i></summary><blockquote>

maybe no, just notify the user that even though seg dup annotation was requested, if no file is provided the job will proceed without it
</blockquote></details>

but if you choose to use that option and do it wrongly by not passing a file, I would expect it to exit instead of silently continuing and not giving the expected output. this is the same as above for mappability.

an `exit 1` would be appropriate, or I'm happy to be persuaded otherwise if you think not :)

**Review by jethror1 — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_prep/2)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @jethror1)

**Review by jethror1 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_prep/2)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @jethror1)

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_prep/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sophie22)

**Pull request merged**
